### ISSUE TITLE
Icons disappeared

### ISSUE THREAD

**Issue by en** [cdot-network/cdot.network#16]
![image](https://user-images.githubusercontent.com/14307069/73684489-3b141c80-46ff-11ea-9ca5-ee24f96492e1.png)
and
![image](https://user-images.githubusercontent.com/14307069/73684511-48c9a200-46ff-11ea-9b54-f8c5d2741f4f.png)

**Comment by himself65** [comment]
Revert version to f4676b6a cause hasn't refactor finished so incorrectly images path
